import { jsPDF } from 'jspdf'
import type { TripRequest, TripResponse } from './types'

const MARGIN = 14
const PAGE_W = 210
const LINE = 6

function addPageIfNeeded(doc: jsPDF, y: number, needed = 20): number {
  if (y + needed > 285) {
    doc.addPage()
    return MARGIN + 10
  }
  return y
}

function wrapText(doc: jsPDF, text: string, x: number, y: number, maxWidth: number): number {
  const lines = doc.splitTextToSize(text, maxWidth)
  lines.forEach((line: string) => {
    doc.text(line, x, y)
    y += LINE
  })
  return y
}

export function exportTripPdf(form: TripRequest, result: TripResponse): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const contentW = PAGE_W - MARGIN * 2
  let y = MARGIN

  doc.setFillColor(13, 27, 62)
  doc.rect(0, 0, PAGE_W, 42, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('WanderGenie', MARGIN, 18)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text(`Trip to ${form.destination}`, MARGIN, 28)
  doc.text(
    `${form.duration} days · ₹${form.budget.toLocaleString('en-IN')} · ${form.interests.join(', ')}`,
    MARGIN,
    35,
  )

  doc.setTextColor(30, 30, 30)
  y = 52

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Weather', MARGIN, y)
  y += LINE + 2
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const w = result.weather
  y = wrapText(
    doc,
    `${w.temperature} · ${w.condition} · Humidity ${w.humidity ?? '—'} · ${w.rainPrediction}`,
    MARGIN,
    y,
    contentW,
  )
  y = wrapText(doc, w.suggestion, MARGIN, y + 2, contentW)
  y += 8

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  y = addPageIfNeeded(doc, y, 30)
  doc.text('Itinerary', MARGIN, y)
  y += LINE + 4

  result.itinerary.forEach((day) => {
    y = addPageIfNeeded(doc, y, 40)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.text(`Day ${day.day}: ${day.title}`, MARGIN, y)
    y += LINE + 1
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    day.activities.forEach((act, i) => {
      y = addPageIfNeeded(doc, y, LINE)
      y = wrapText(doc, `${i + 1}. ${act}`, MARGIN + 2, y, contentW - 2)
    })
    if (day.meals) {
      y = addPageIfNeeded(doc, y, LINE * 3)
      y = wrapText(
        doc,
        `Meals — Breakfast: ${day.meals.breakfast} | Lunch: ${day.meals.lunch} | Dinner: ${day.meals.dinner}`,
        MARGIN + 2,
        y,
        contentW - 2,
      )
    }
    if (day.tips) {
      y = addPageIfNeeded(doc, y, LINE * 2)
      y = wrapText(doc, `Tip: ${day.tips}`, MARGIN + 2, y, contentW - 2)
    }
    y += 6
  })

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  y = addPageIfNeeded(doc, y, 20)
  doc.text('Packing List', MARGIN, y)
  y += LINE + 4

  result.packing_list.forEach((section) => {
    y = addPageIfNeeded(doc, y, 20)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.text(section.name, MARGIN, y)
    y += LINE
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    section.items.forEach((item) => {
      y = addPageIfNeeded(doc, y, LINE)
      doc.text(`• ${item}`, MARGIN + 3, y)
      y += LINE
    })
    y += 4
  })

  doc.setFontSize(8)
  doc.setTextColor(120, 120, 120)
  y = addPageIfNeeded(doc, y, 10)
  doc.text('Generated by WanderGenie — wander-genie', MARGIN, y)

  const safeName = form.destination.replace(/[^\w\-]+/g, '-').toLowerCase()
  doc.save(`WanderGenie-${safeName}-trip.pdf`)
}
